CREATE TABLE carts(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_in_cents INT NOT NULL DEFAULT 0 CHECK (total_in_cents >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TYPE cart_item_type AS ENUM ('product', 'recipe');

CREATE TABLE cart_items(
    cart_id INT,
    item_id INT NOT NULL,
    item_type cart_item_type NOT NULL,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (cart_id, item_id, item_type),
    FOREIGN KEY (cart_id) REFERENCES carts(id)
);
